### ISSUE TITLE
[CY-6261] Version is not getting update

### ISSUE THREAD

**Issue by faiqsayed** [codacy/git-version#59]
Hi, 
I am trying to use this tool but I am unable to configure it. I have tried recommended code in my workflow but it is not updating anything.
I am not sure why the documentation is not reflecting the simple and basic setting to use this tool.
Please have a look at my code and let me know the solution.

Thanks in advance.

```
- name: Git Version
        id: get-version
        uses: codacy/git-version@2.2.0
        with:
          prefix: v
          release-branch: main
          dev-branch: feature/**

      - name: New Version
        run: echo ${{ steps.get-version.outputs.version }}
```
