### ISSUE TITLE
Document access to version

### ISSUE THREAD

**Issue by francisdb** [codacy/git-version#63]
eg for pushing docker images

```yaml
      - name: Git Version
        uses: codacy/git-version@2.5.4
        id: gitversion

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: myrepo.com/myimage:${{ steps.gitversion.outputs.version }}
```
