### ISSUE TITLE
Expose non-prefixed version number in the output

### ISSUE THREAD

**Issue by tanordheim** [codacy/git-version#78]
If using a configuration like this:

```yaml
      - name: Get build version
        uses: codacy/git-version@2.7.1
        id: version
        with:
          log-paths: 'module1'
          prefix: module1-
```

Then `steps.version.outputs.version` outputs something like `module1-0.0.1-...`. It would be super great to be able to access the non-prefixed version number here as well, usecase is building NuGet packages where we need the actual version number without prefix as a prefixed version number like this is not accepted.
