### ISSUE TITLE
Monorepo prefix does not pick up last version.

### ISSUE THREAD

**Issue by Gander7** [codacy/git-version#81]
Scenario, A repo with multiple libraries within (one per folder)

- Library1/
- Library2/
- Library3/

I already have the following tags on the relevant commits for each version. These pre-existed using `git-version` and were done manually.

- `Library1/v1.0.1`
- `Library1/v1.0.0`

- `Library2/v1.0.0`

- `Library3/v1.0.0`
- `Library3/v1.1.0`
- `Library3/v1.1.1`

I'm trying to implement `git-version` to get the next version for Library3.

```yml
    - name: Git Version
      uses: codacy/git-version@2.8.0
      with:
        log-paths: Library3/
        prefix: Library3/v
 ```
 
 It attempts to version Library3 as v0.0.1
 
 ```console
Run codacy/git-version@2.8.0
Run set -eo pipefail
Run set -eo pipefail
Previous Version: Library3/v0.0.0
Run set -eo pipefail
New Version: Library3/v0.0.1-testbranch.1.bb3d664
 ```
 
 Expected: That the Previous version is detected as `Library3/v1.1.1` and the new version should start with `Library3/v1.1.2`

I'm not sure if `git-version` just looks at the last tag, this may or may not be the last version.
