### ISSUE TITLE
Commit messages being downcased before comparison

### ISSUE THREAD

**Issue by lwbrooke** [codacy/git-version#88]
For both regex and plain string comparison, the commit messages are being [downcased](https://github.com/codacy/git-version/blob/master/src/git-version.cr#L148-L152C18). This means that when overriding the major and minor identifiers, one cannot use uppercase identifiers, such as MAJOR and MINOR.

As far as I can tell, this is not documented behavior.

**Comment by msfe** [comment]
If anyone else would run into this with issues you can let your regex ignore casing with something like this. In my case i want it to start with Minor: or MAJOR: with any casing but you can modify according to your purpose.

```
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          minor-identifier: /(?i)^minor:/
          major-identifier: /(?i)^major:/
```
