### ISSUE TITLE
Invalid version release-branch

### ISSUE THREAD

**Issue by zyexal** [codacy/git-version#89]
I have noticed that the `outputs.version` on the release-branch can be invalid.

Observed scenario:
- The project has a single existing tag `0.0.1` and a release-branch named `main` 
- The `codacy/git-version@2.7.1` output on `main`:
  - received:
`Previous Version: 0.0.0`
`New Version: 0.0.1`
  - expected:
`Previous Version: 0.0.1`
`New Version: 0.0.2`

After adding another tag `0.0.2` I got the output:
- as expected
`Previous Version: 0.0.2`
`New Version: 0.0.3`

This cause me to assure, that at least two tags exists before being able to use the `codacy/git-version@2.7.1`

**Comment by skraussppro** [comment]
Folks I could find out, that the issue is related to the usage of `s4u/setup-maven-action@v1.10.0`

Causes the issue:
```
      - name: Prepare Maven
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Check Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
```

Does not cause the issue
```
      - name: Check Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          
      - name: Prepare Maven
        uses: s4u/setup-maven-action@v1.10.0
        with:
          java-version: ${{env.JAVA_VERSION}}
```
